import { formatCurrency } from '../utils/helpers';

interface PDFReportData {
  title: string;
  subtitle?: string;
  dateRange?: string;
  businessName: string;
  columns: string[];
  rows: (string | number)[][];
  summary?: { label: string; value: string }[];
}

export function generateReportPDF(data: PDFReportData) {
  const tableRows = data.rows.map(row =>
    `<tr>${row.map((cell, i) =>
      `<td style="padding:8px;border-bottom:1px solid #eee;text-align:${i === 0 ? 'left' : 'right'};font-size:12px">${cell}</td>`
    ).join('')}</tr>`
  ).join('');

  const summaryRows = (data.summary || []).map(s =>
    `<tr><td style="padding:4px 8px;font-weight:bold;font-size:13px">${s.label}</td><td style="padding:4px 8px;text-align:right;font-weight:bold;font-size:13px">${s.value}</td></tr>`
  ).join('');

  const html = `<!DOCTYPE html>
<html><head><style>
  body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
  .header { text-align: center; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 2px solid #2563EB; }
  .header h1 { margin: 0; font-size: 22px; color: #2563EB; }
  .header p { margin: 4px 0; font-size: 12px; color: #666; }
  table { width: 100%; border-collapse: collapse; margin-top: 15px; }
  th { padding: 10px 8px; text-align: left; background: #f8f9fa; font-size: 11px; text-transform: uppercase; color: #666; border-bottom: 2px solid #dee2e6; }
  th:not(:first-child) { text-align: right; }
  .summary { margin-top: 20px; padding: 15px; background: #f8f9fa; border-radius: 8px; }
  .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; }
  @media print { body { margin: 0; } .no-print { display: none; } }
</style></head><body>
  <div class="header">
    <h1>${data.businessName}</h1>
    <p style="font-size:16px;font-weight:bold;margin-top:8px">${data.title}</p>
    ${data.subtitle ? `<p>${data.subtitle}</p>` : ''}
    ${data.dateRange ? `<p>Period: ${data.dateRange}</p>` : ''}
    <p>Generated: ${new Date().toLocaleString()}</p>
  </div>
  <table>
    <thead><tr>${data.columns.map((c, i) => `<th${i > 0 ? ' style="text-align:right"' : ''}>${c}</th>`).join('')}</tr></thead>
    <tbody>${tableRows}</tbody>
  </table>
  ${summaryRows ? `<div class="summary"><table>${summaryRows}</table></div>` : ''}
  <div class="footer"><p>This report was generated by MyPOS &mdash; ${data.businessName}</p></div>
  <script class="no-print">window.onload=()=>window.print();</script>
</body></html>`;

  const w = window.open('', '_blank', 'width=800,height=600');
  if (w) {
    w.document.write(html);
    w.document.close();
  }
}

export function exportOrdersReport(orders: any[], businessName: string) {
  generateReportPDF({
    title: 'Orders Report',
    businessName,
    columns: ['Order #', 'Date', 'Customer', 'Items', 'Total', 'Status'],
    rows: orders.map(o => [
      o.orderNumber,
      new Date(o.createdAt).toLocaleDateString(),
      o.customer ? `${o.customer.firstName} ${o.customer.lastName || ''}` : 'Walk-in',
      o.items?.length || 0,
      formatCurrency(o.totalAmount),
      o.status,
    ]),
    summary: [
      { label: 'Total Orders', value: String(orders.length) },
      { label: 'Total Revenue', value: formatCurrency(orders.reduce((s, o) => s + o.totalAmount, 0)) },
    ],
  });
}

export function exportProductsReport(products: any[], businessName: string) {
  generateReportPDF({
    title: 'Products Report',
    businessName,
    columns: ['Product', 'SKU', 'Category', 'Price', 'Cost', 'Margin'],
    rows: products.map(p => [
      p.name,
      p.sku || '-',
      p.category?.name || '-',
      formatCurrency(p.price),
      p.costPrice ? formatCurrency(p.costPrice) : '-',
      p.costPrice ? `${Math.round(((p.price - p.costPrice) / p.price) * 100)}%` : '-',
    ]),
  });
}

export function exportInventoryReport(inventory: any[], businessName: string) {
  generateReportPDF({
    title: 'Inventory Report',
    businessName,
    columns: ['Product', 'SKU', 'Stock', 'Min Level', 'Status', 'Expiry'],
    rows: inventory.map(i => [
      i.product?.name || 'Unknown',
      i.product?.sku || '-',
      i.quantity,
      i.minStock,
      i.quantity <= i.minStock ? 'LOW' : 'OK',
      i.expiryDate ? new Date(i.expiryDate).toLocaleDateString() : '-',
    ]),
  });
}
